name: Build and Test
on:
  push:
    branches:
      - main
  pull_request: 
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Install deps
        run: npm install
      - name: Run all the test 
        run: npm test
        
      
          
          
          
          
          
          
